// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package di

import (
	"github.com/fengyoutian/holingo-micro-gin/micro-server/internal/server/grpc"
	"github.com/fengyoutian/holingo-micro-gin/micro-server/internal/service"
)

// Injectors from wire.go:

func InitApp() (*App, func(), error) {
	serviceService, cleanup, err := service.New()
	if err != nil {
		return nil, nil, err
	}
	microService, err := grpc.New(serviceService)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	app, cleanup2, err := NewApp(serviceService, microService)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
