client:
  dialect: "mysql"
  addr: "192.168.222.110:3306"
  #	dsn: "{user}:{password}@tcp(127.0.0.1:3306)/{database}?timeout=1s&readTimeout=1s&writeTimeout=1s&parseTime=true&loc=Local&charset=utf8mb4,utf8"
  dsn: "root:root@tcp(192.168.222.110:3306)/holingo?timeout=1s&readTimeout=1s&writeTimeout=1s&parseTime=true&loc=Local&charset=utf8mb4,utf8"
  max_open_conns: 10
  max_idle_conns: 1
  conn_max_life_time: 7200
