// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package holingo_v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HelloReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloReq) Reset()         { *m = HelloReq{} }
func (m *HelloReq) String() string { return proto.CompactTextString(m) }
func (*HelloReq) ProtoMessage()    {}
func (*HelloReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *HelloReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloReq.Unmarshal(m, b)
}
func (m *HelloReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloReq.Marshal(b, m, deterministic)
}
func (m *HelloReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloReq.Merge(m, src)
}
func (m *HelloReq) XXX_Size() int {
	return xxx_messageInfo_HelloReq.Size(m)
}
func (m *HelloReq) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloReq.DiscardUnknown(m)
}

var xxx_messageInfo_HelloReq proto.InternalMessageInfo

func (m *HelloReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HelloResp struct {
	Content              string   `protobuf:"bytes,1,opt,name=Content,proto3" json:"Content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloResp) Reset()         { *m = HelloResp{} }
func (m *HelloResp) String() string { return proto.CompactTextString(m) }
func (*HelloResp) ProtoMessage()    {}
func (*HelloResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *HelloResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloResp.Unmarshal(m, b)
}
func (m *HelloResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloResp.Marshal(b, m, deterministic)
}
func (m *HelloResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloResp.Merge(m, src)
}
func (m *HelloResp) XXX_Size() int {
	return xxx_messageInfo_HelloResp.Size(m)
}
func (m *HelloResp) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloResp.DiscardUnknown(m)
}

var xxx_messageInfo_HelloResp proto.InternalMessageInfo

func (m *HelloResp) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type Article struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Author               string   `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Content              string   `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	ModifyTime           string   `protobuf:"bytes,5,opt,name=modify_time,json=modifyTime,proto3" json:"modify_time,omitempty"`
	CreateTime           string   `protobuf:"bytes,6,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Article) Reset()         { *m = Article{} }
func (m *Article) String() string { return proto.CompactTextString(m) }
func (*Article) ProtoMessage()    {}
func (*Article) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *Article) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Article.Unmarshal(m, b)
}
func (m *Article) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Article.Marshal(b, m, deterministic)
}
func (m *Article) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Article.Merge(m, src)
}
func (m *Article) XXX_Size() int {
	return xxx_messageInfo_Article.Size(m)
}
func (m *Article) XXX_DiscardUnknown() {
	xxx_messageInfo_Article.DiscardUnknown(m)
}

var xxx_messageInfo_Article proto.InternalMessageInfo

func (m *Article) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Article) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *Article) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Article) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Article) GetModifyTime() string {
	if m != nil {
		return m.ModifyTime
	}
	return ""
}

func (m *Article) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloReq)(nil), "holingo.v1.HelloReq")
	proto.RegisterType((*HelloResp)(nil), "holingo.v1.HelloResp")
	proto.RegisterType((*Article)(nil), "holingo.v1.Article")
}

func init() {
	proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c)
}

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 309 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x90, 0x4f, 0x4b, 0xf3, 0x40,
	0x10, 0xc6, 0x9b, 0xbe, 0xe9, 0xbf, 0x79, 0xd1, 0xc3, 0x58, 0x4b, 0x88, 0xa0, 0xb2, 0x20, 0x78,
	0xda, 0xa2, 0x5e, 0x2a, 0x9e, 0x8a, 0x08, 0x3d, 0x4a, 0xeb, 0x5d, 0xb6, 0xc9, 0x34, 0x5d, 0xd8,
	0x64, 0x63, 0xba, 0x15, 0xf2, 0x79, 0xfc, 0x8c, 0xde, 0x25, 0xbb, 0x1b, 0xf4, 0x50, 0x2f, 0xde,
	0xf6, 0x79, 0xe6, 0x37, 0x0c, 0xfb, 0x83, 0x91, 0x28, 0x25, 0x2f, 0x2b, 0x6d, 0x34, 0xc2, 0x56,
	0x2b, 0x59, 0x64, 0x9a, 0xbf, 0xdf, 0xc4, 0x67, 0x99, 0xd6, 0x99, 0xa2, 0xa9, 0x9d, 0xac, 0xf7,
	0x9b, 0x29, 0xe5, 0xa5, 0xa9, 0x1d, 0xc8, 0xce, 0x61, 0xb8, 0x20, 0xa5, 0xf4, 0x92, 0xde, 0x10,
	0x21, 0x2c, 0x44, 0x4e, 0x51, 0x70, 0x19, 0x5c, 0x8f, 0x96, 0xf6, 0xcd, 0xae, 0x60, 0xe4, 0xe7,
	0xbb, 0x12, 0x23, 0x18, 0x3c, 0xea, 0xc2, 0x50, 0x61, 0x3c, 0xd3, 0x46, 0xf6, 0x11, 0xc0, 0x60,
	0x5e, 0x19, 0x99, 0x28, 0xc2, 0x63, 0xe8, 0xca, 0xd4, 0x02, 0xe1, 0xb2, 0x2b, 0x53, 0x9c, 0x40,
	0x5f, 0xec, 0xcd, 0x56, 0x57, 0x51, 0xd7, 0x2e, 0xf9, 0x84, 0x63, 0xe8, 0x19, 0x69, 0x14, 0x45,
	0xff, 0x6c, 0xed, 0x42, 0x73, 0x23, 0xf1, 0x37, 0x42, 0x77, 0xc3, 0x47, 0xbc, 0x80, 0xff, 0xb9,
	0x4e, 0xe5, 0xa6, 0x7e, 0x35, 0x32, 0xa7, 0xa8, 0x67, 0xa7, 0xe0, 0xaa, 0x17, 0x99, 0x53, 0x03,
	0x24, 0x15, 0x09, 0x43, 0x0e, 0xe8, 0x3b, 0xc0, 0x55, 0x0d, 0x70, 0xfb, 0x19, 0xc0, 0x60, 0xe1,
	0xc4, 0xe0, 0x0c, 0xc2, 0x67, 0x59, 0x64, 0x38, 0xe1, 0x4e, 0x0f, 0x6f, 0xf5, 0xf0, 0xa7, 0x46,
	0x4f, 0xfc, 0x4b, 0xcf, 0x3a, 0x78, 0x0f, 0xc3, 0x95, 0xa8, 0xad, 0x15, 0x1c, 0xf3, 0x6f, 0xd1,
	0xbc, 0x15, 0x19, 0x9f, 0x1e, 0x68, 0x77, 0x25, 0xeb, 0xe0, 0x0c, 0x60, 0x9e, 0xa6, 0xad, 0xa8,
	0x93, 0x9f, 0x98, 0x2f, 0xe3, 0x43, 0x25, 0xeb, 0xe0, 0x03, 0x1c, 0xad, 0x48, 0x54, 0xc9, 0xf6,
	0x0f, 0xcb, 0xeb, 0xbe, 0xfd, 0xc3, 0xdd, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x30, 0xff, 0xf6,
	0x0b, 0x21, 0x02, 0x00, 0x00,
}
